FROM rust:1.59.0 as builder
RUN useradd -ms /bin/bash dashie

WORKDIR /app
RUN rustup component add rustfmt \
    && cargo install cargo-watch

ADD --chown=dashie:dashie . ./
RUN chown -R dashie:staff /app
RUN chown -R dashie:staff /usr/local/cargo
RUN chmod 755 /app
USER dashie

EXPOSE 3000
