FROM rustlang/rust:nightly-slim as builder
RUN useradd -ms /bin/bash dashie

WORKDIR /auth
RUN rustup component add rustfmt \
    && cargo install cargo-watch

ADD --chown=dashie:dashie . ./
RUN chown -R dashie:staff /auth
RUN chown -R dashie:staff /usr/local/cargo
RUN chmod 755 /auth
USER dashie

EXPOSE 3000
