version: '3'
services:
  rust-api:
    build:
      context: .
      dockerfile: Dockerfile_dev
    ports:
      - "50051:50051"
    environment:
      - PORT=9001
      - MONGO_HOST=example-db
      - MONGO_PORT=27017
    command: cargo watch -x run
    user: root
    volumes:
        - ./:/auth:rw,cached
        - ./target:/auth/target:rw,delegated
        - registry:/root/.cargo/registry
    links:
        - mongodb
    depends_on: 
        - mongodb
    networks:
      - default

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - example-db:/example-db/db
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  example-db:
  registry:
