version: '3'
services:
  auth-api:
    build:
      context: .
      dockerfile: Dockerfile_dev
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    command: cargo watch -x "run"
    user: ${CURRENT_UID}
    volumes:
        - .:/app
        - registry:/root/.cargo/registry
    links:
        - mongodb
    depends_on: 
        - mongodb
    networks:
      - default

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - example-db:/example-db/db
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  example-db:
  registry:
    driver: local
